### ISSUE TITLE
No such file or directory errors on make starter

### ISSUE THREAD

**Issue by aOelschlager** [Islandora-Devops/isle-dc#380] opened 2024-03-07 16:39 UTC
I have not experienced this myself, but this error has been reported multiple times on Slack.
`docker compose exec -T drupal with-contenv bash -lc 'chown -R nginx:nginx . ; echo "Chown Complete"'
s6-envdir: fatal: unable to envdir: No such file or directory
make[1]: *** [Makefile:564: starter-finalize] Error 111
make[1]: Leaving directory `
That same error had happened with starter_dev and was fixed with a loop that checks if the directory is available before running the command: https://github.com/Islandora-Devops/isle-dc/blob/development/Makefile#L172-L176. This error started to show up with the 2.x and 3.x images.

Temporary fix has been to have people run make starter_dev instead.

**Comment by pennedav** [comment] 2024-04-17 17:36
I've run into this issue myself. (Among others trying to get Islandora setup using ISLE-DC.)
Steps to reproduce for me (on Debian 11, docker version 26, docker compose 2.25, installed from https://download.docker.com/linux/debian):

Following directions on this page:
https://islandora.github.io/documentation/installation/docker-local/

clone the isle-dc repo
customize .env
make starter

That's literally it to reproduce the issue in the OP.

I can get a starter site running by just re-running make starter.

I get stuck later on trying to build a custom image per the instructions here, however:

https://islandora.github.io/documentation/installation/docker-custom/

The build works fine, but then trying to run make production fails to start the drupal container because of a permissions error.

I was able to get past this by making sure the build/rootfs/etc/cont-init.s/04-custom-setup.sh file had execute permissions set.

At this point starting the drupal container gets further, but still fails when setting up the database. 
The error is related to it trying to connect as root to the database with password "password".

So clearly something is preventing the secrets from being used.

This whole setup seems to be horribly broken. Is anybody maintaining this anymore?

**Comment by joecorall** [comment] 2024-04-18 14:58
@aOelschlager  - thanks for starting this issue!

@pennedav - thanks for reporting the issues you experienced. I believe the changes in https://github.com/Islandora-Devops/isle-dc/pull/384 should resolve the issues you were seeing. Once the PR has been reviewed/tested those changes will be merged into the default branch in this repo.

As far as the maintenance status of this repository: I think often issues are only discovered when first setting up an environment. After which things "just work" but as time goes on configuration drifts for new builds and new issues are not detected until an existing maintainer has a reason to build a new environment or someone tries Islandora for the first time. As a preventative measure I also added a nightly test to the PR that will report issues in the Islandora slack channel for new builds in this repo. Hopefully that mechanism will be approved in the PR, and will help detect issues with new builds faster to avoid others from experiencing the types of issues you reported.

**Closed as completed** 2024-04-19 02:25 UTC
